/**
 * Auto-generated by scripts/build-images.mjs — do not edit manually.
 *
 * Image asset URLs are namespaced under /explainers/longevity/processed/
 * so multiple essays can ship their own image manifests without colliding.
 */
import type { ImageEntry } from '$lib/types/explainer';

export type { ImageEntry } from '$lib/types/explainer';

export const imageManifest: ImageEntry[] = [
  {
    "name": "longevity-couple-walking",
    "width": 3000,
    "height": 1993,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-couple-walking-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-couple-walking-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-couple-walking-1200w.webp"
      }
    ],
    "blurhash": "C4D9SA?I00}uJBx@$,E1"
  },
  {
    "name": "longevity-grandpa-running",
    "width": 1362,
    "height": 2040,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-grandpa-running-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-grandpa-running-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-grandpa-running-1200w.webp"
      }
    ],
    "blurhash": "mVMZ:Mt2~oM{9HRkR.RjtURmIts.tdWAt6axS5oexaa#RRjF%Loe"
  },
  {
    "name": "longevity-leg-cast",
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-leg-cast-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-leg-cast-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-leg-cast-1200w.webp"
      }
    ],
    "blurhash": "LEFFNm00}??b00_NMyMx#QE2X9={"
  },
  {
    "name": "longevity-okinawa-village",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-okinawa-village-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-okinawa-village-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-okinawa-village-1200w.webp"
      }
    ],
    "blurhash": "C6A^dpo|8{0000Ip~X?c"
  },
  {
    "name": "longevity-sleep",
    "width": 3985,
    "height": 3024,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-sleep-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-sleep-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-sleep-1200w.webp"
      }
    ],
    "blurhash": "LsNK3Tx]~qt7%3ozWVRjx]WBM{of"
  },
  {
    "name": "longevity-walking-frame",
    "width": 7000,
    "height": 4836,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-walking-frame-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-walking-frame-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-walking-frame-1200w.webp"
      }
    ],
    "blurhash": "CFGuE.}+ovET180K?9o$"
  },
  {
    "name": "longevity-women-exercise",
    "width": 2700,
    "height": 1800,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-women-exercise-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-women-exercise-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-women-exercise-1200w.webp"
      }
    ],
    "blurhash": "C6Eo74~C9wTHy=?b$,yD"
  }
];
