/**
 * Auto-generated by scripts/build-images.mjs — do not edit manually.
 *
 * Image asset URLs are namespaced under /explainers/longevity/processed/
 * so multiple essays can ship their own image manifests without colliding.
 */
import type { ImageEntry } from '$lib/types/explainer';

export type { ImageEntry } from '$lib/types/explainer';

export const imageManifest: ImageEntry[] = [
  {
    "name": "L1040910",
    "width": 3832,
    "height": 5757,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/L1040910-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/L1040910-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/L1040910-1200w.webp"
      }
    ],
    "blurhash": "mnF=~-%2azof_Nt7aykC9vR*f5ay4.RjjsayaJj@j[js-oofflj["
  },
  {
    "name": "balance",
    "width": 1971,
    "height": 1478,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/balance-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/balance-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/balance-1200w.webp"
      }
    ],
    "blurhash": "L5Ci,Sr9lB?a0A00E7%3?X_NnLMy"
  },
  {
    "name": "centre-for-ageing-better-REIecbS8XQY-unsplash",
    "width": 6000,
    "height": 4000,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/centre-for-ageing-better-REIecbS8XQY-unsplash-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/centre-for-ageing-better-REIecbS8XQY-unsplash-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/centre-for-ageing-better-REIecbS8XQY-unsplash-1200w.webp"
      }
    ],
    "blurhash": "CEE.FF}?xBxI1HFt9u-o"
  },
  {
    "name": "diet",
    "width": 5184,
    "height": 3456,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/diet-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/diet-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/diet-1200w.webp"
      }
    ],
    "blurhash": "CHFrkTn~kItP~ps,x]OE"
  },
  {
    "name": "healthy-habit",
    "width": 6000,
    "height": 4000,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/healthy-habit-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/healthy-habit-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/healthy-habit-1200w.webp"
      }
    ],
    "blurhash": "C49*q_.N9YcP*Eo|VcX2"
  },
  {
    "name": "jon-bovi",
    "width": 900,
    "height": 1200,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/jon-bovi-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/jon-bovi-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/jon-bovi-1200w.webp"
      }
    ],
    "blurhash": "dKM=|E9b0LIp~B$%IVxZ?Yj]D*xZ%Lt6Rja{9vs:n+WV"
  },
  {
    "name": "lifestyle-pattern",
    "width": 2587,
    "height": 3880,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/lifestyle-pattern-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/lifestyle-pattern-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/lifestyle-pattern-1200w.webp"
      }
    ],
    "blurhash": "mFH_Y$~C5W%Nt-%gxuS457S#%1xatRS%ogWCg2xtt7sp$Os:%L%M"
  },
  {
    "name": "longevity-altamira-cave",
    "width": 5000,
    "height": 3328,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-altamira-cave-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-altamira-cave-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-altamira-cave-1200w.webp"
      }
    ],
    "blurhash": "C8HSr-Vv0%%0}EENxrI="
  },
  {
    "name": "longevity-aylesbury-estate",
    "width": 2304,
    "height": 3072,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-aylesbury-estate-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-aylesbury-estate-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-aylesbury-estate-1200w.webp"
      }
    ],
    "blurhash": "dtHC4V^,tRRj~q-;t7j@t7t7oLt6V@fkWBWBWBWBRjWB"
  },
  {
    "name": "longevity-couple-walking",
    "width": 3000,
    "height": 1993,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-couple-walking-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-couple-walking-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-couple-walking-1200w.webp"
      }
    ],
    "blurhash": "C4D9SA?I00}uJBx@$,E1"
  },
  {
    "name": "longevity-grandpa-running",
    "width": 1362,
    "height": 2040,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-grandpa-running-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-grandpa-running-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-grandpa-running-1200w.webp"
      }
    ],
    "blurhash": "mVMZ:Mt2~oM{9HRkR.RjtURmIts.tdWAt6axS5oexaa#RRjF%Loe"
  },
  {
    "name": "longevity-leg-cast",
    "width": 4032,
    "height": 3024,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-leg-cast-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-leg-cast-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-leg-cast-1200w.webp"
      }
    ],
    "blurhash": "LEFFNm00}??b00_NMyMx#QE2X9={"
  },
  {
    "name": "longevity-okinawa-village",
    "width": 1920,
    "height": 1080,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-okinawa-village-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-okinawa-village-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-okinawa-village-1200w.webp"
      }
    ],
    "blurhash": "C6A^dpo|8{0000Ip~X?c"
  },
  {
    "name": "longevity-sleep",
    "width": 3985,
    "height": 3024,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-sleep-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-sleep-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-sleep-1200w.webp"
      }
    ],
    "blurhash": "LsNK3Tx]~qt7%3ozWVRjx]WBM{of"
  },
  {
    "name": "longevity-strength-training",
    "width": 3496,
    "height": 2268,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-strength-training-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-strength-training-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-strength-training-1200w.webp"
      }
    ],
    "blurhash": "CuJHt5IAS5xa?waJjYRk"
  },
  {
    "name": "longevity-walking-frame",
    "width": 7000,
    "height": 4836,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-walking-frame-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-walking-frame-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-walking-frame-1200w.webp"
      }
    ],
    "blurhash": "CFGuE.}+ovET180K?9o$"
  },
  {
    "name": "longevity-women-exercise",
    "width": 2700,
    "height": 1800,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/longevity-women-exercise-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/longevity-women-exercise-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/longevity-women-exercise-1200w.webp"
      }
    ],
    "blurhash": "C6Eo74~C9wTHy=?b$,yD"
  },
  {
    "name": "okinawa",
    "width": 2000,
    "height": 1300,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/okinawa-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/okinawa-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/okinawa-1200w.webp"
      }
    ],
    "blurhash": "CNFXq}xwpItl~AtP%1xu"
  },
  {
    "name": "stress",
    "width": 2667,
    "height": 1785,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/longevity/processed/stress-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/longevity/processed/stress-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/longevity/processed/stress-1200w.webp"
      }
    ],
    "blurhash": "CADv$T~pV@%gxTxZMxRj"
  }
];
