/**
 * Auto-generated by scripts/build-images.mjs — do not edit manually.
 *
 * Image asset URLs are namespaced under /explainers/ultra-processed/processed/
 * so multiple essays can ship their own image manifests without colliding.
 */
import type { ImageEntry } from '$lib/types/explainer';

export type { ImageEntry } from '$lib/types/explainer';

export const imageManifest: ImageEntry[] = [
  {
    "name": "chris-van-tulleken",
    "width": 1440,
    "height": 1080,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/ultra-processed/processed/chris-van-tulleken-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/ultra-processed/processed/chris-van-tulleken-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/ultra-processed/processed/chris-van-tulleken-1200w.webp"
      }
    ],
    "blurhash": "LcLDoi0fbH$L~q%2j[W;yEV?ayo#"
  },
  {
    "name": "upf-bread",
    "width": 1200,
    "height": 801,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/ultra-processed/processed/upf-bread-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/ultra-processed/processed/upf-bread-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/ultra-processed/processed/upf-bread-1200w.webp"
      }
    ],
    "blurhash": "CJOekX~T4Urr=X-oxZR-"
  },
  {
    "name": "upf-factory",
    "width": 620,
    "height": 400,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/ultra-processed/processed/upf-factory-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/ultra-processed/processed/upf-factory-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/ultra-processed/processed/upf-factory-1200w.webp"
      }
    ],
    "blurhash": "CGHdvf00ysrVYj4o-;In"
  },
  {
    "name": "upf-healthy",
    "width": 599,
    "height": 722,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/ultra-processed/processed/upf-healthy-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/ultra-processed/processed/upf-healthy-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/ultra-processed/processed/upf-healthy-1200w.webp"
      }
    ],
    "blurhash": "UNH.H0~p00Qm9dbcD%E29ZM{x]Sh%Lt6V?sm"
  },
  {
    "name": "upf-kellogs",
    "width": 2400,
    "height": 2400,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/ultra-processed/processed/upf-kellogs-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/ultra-processed/processed/upf-kellogs-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/ultra-processed/processed/upf-kellogs-1200w.webp"
      }
    ],
    "blurhash": "UZLpA^~20yNa+JNIOqo|mpg2kRRk+]V{Shxo"
  },
  {
    "name": "upf-pile",
    "width": 1024,
    "height": 629,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/ultra-processed/processed/upf-pile-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/ultra-processed/processed/upf-pile-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/ultra-processed/processed/upf-pile-1200w.webp"
      }
    ],
    "blurhash": "C3G8ZSuj4=yB~C0JN9-E"
  },
  {
    "name": "upf-supermarket",
    "width": 2242,
    "height": 1378,
    "variants": [
      {
        "width": 400,
        "src": "/explainers/ultra-processed/processed/upf-supermarket-400w.webp"
      },
      {
        "width": 800,
        "src": "/explainers/ultra-processed/processed/upf-supermarket-800w.webp"
      },
      {
        "width": 1200,
        "src": "/explainers/ultra-processed/processed/upf-supermarket-1200w.webp"
      }
    ],
    "blurhash": "C3G8ZRuj57%d~C0JRc-E"
  }
];
