/**
 * scripts/build-images.mjs
 *
 * Walks every explainer's `static/explainers/<slug>/images/` directory,
 * pre-processes each source image, and writes a typed manifest into
 * `src/lib/explainers/<slug>/image-manifest.ts`.
 *
 * For every image it produces:
 *   1. A short blurhash string used as the LQIP placeholder.
 *   2. Responsive WebP variants at 400w / 800w / 1200w, saved next to the
 *      originals under `static/explainers/<slug>/processed/`.
 *
 * Run automatically before `vite build` via the `build` npm script.
 *
 * Usage:
 *   node scripts/build-images.mjs           # process every explainer
 *   node scripts/build-images.mjs --slug=longevity   # one only
 */

import sharp from 'sharp';
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync, existsSync } from 'fs';
import { join, dirname, extname, basename } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const STATIC_DIR = join(ROOT, 'static');
const EXPLAINERS_STATIC_DIR = join(STATIC_DIR, 'explainers');
const EXPLAINERS_LIB_DIR = join(ROOT, 'src', 'lib', 'explainers');

/** Responsive breakpoints for srcset */
const WIDTHS = [400, 800, 1200];

/** File extensions we'll attempt to process. */
const SUPPORTED_EXTS = new Set(['.png', '.jpg', '.jpeg', '.webp', '.avif']);

// ----------------------------------------------------------------------------
// CLI args
// ----------------------------------------------------------------------------

const args = process.argv.slice(2);
const slugFilter = (() => {
	const arg = args.find((a) => a.startsWith('--slug='));
	return arg ? arg.slice('--slug='.length) : null;
})();

// ----------------------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------------------

async function generateBlurhash(buffer) {
	const { encode } = await import('blurhash');
	const { data, info } = await sharp(buffer)
		.resize({ width: 32, withoutEnlargement: true })
		.ensureAlpha()
		.raw()
		.toBuffer({ resolveWithObject: true });

	const cx = Math.min(9, Math.max(1, Math.floor(info.width / 8) || 1));
	const cy = Math.min(9, Math.max(1, Math.floor(info.height / 8) || 1));
	return encode(new Uint8ClampedArray(data), info.width, info.height, cx, cy);
}

async function processImage({ slug, srcAbs, name }) {
	const outputDir = join(EXPLAINERS_STATIC_DIR, slug, 'processed');
	mkdirSync(outputDir, { recursive: true });

	const buffer = readFileSync(srcAbs);
	const meta = await sharp(buffer).metadata();

	const result = { name, width: meta.width, height: meta.height, variants: [], blurhash: '' };

	result.blurhash = await generateBlurhash(buffer);

	for (const w of WIDTHS) {
		const outName = `${name}-${w}w.webp`;
		const outPath = join(outputDir, outName);
		await sharp(buffer)
			.resize({ width: w, withoutEnlargement: true })
			.webp({ quality: 80 })
			.toFile(outPath);
		result.variants.push({ width: w, src: `/explainers/${slug}/processed/${outName}` });
	}

	return result;
}

function listExplainerSlugs() {
	if (!existsSync(EXPLAINERS_STATIC_DIR)) return [];
	return readdirSync(EXPLAINERS_STATIC_DIR).filter((entry) => {
		const full = join(EXPLAINERS_STATIC_DIR, entry);
		return statSync(full).isDirectory();
	});
}

function listSourceImages(slug) {
	const imagesDir = join(EXPLAINERS_STATIC_DIR, slug, 'images');
	if (!existsSync(imagesDir)) return [];
	return readdirSync(imagesDir)
		.filter((f) => SUPPORTED_EXTS.has(extname(f).toLowerCase()))
		.map((f) => ({
			srcAbs: join(imagesDir, f),
			name: basename(f, extname(f))
		}));
}

function writeManifest(slug, manifest) {
	const targetDir = join(EXPLAINERS_LIB_DIR, slug);
	mkdirSync(targetDir, { recursive: true });
	const targetPath = join(targetDir, 'image-manifest.ts');

	const contents = `/**
 * Auto-generated by scripts/build-images.mjs — do not edit manually.
 *
 * Image asset URLs are namespaced under /explainers/${slug}/processed/
 * so multiple essays can ship their own image manifests without colliding.
 */
import type { ImageEntry } from '$lib/types/explainer';

export type { ImageEntry } from '$lib/types/explainer';

export const imageManifest: ImageEntry[] = ${JSON.stringify(manifest, null, 2)};
`;
	writeFileSync(targetPath, contents);
	return targetPath;
}

// ----------------------------------------------------------------------------
// Run
// ----------------------------------------------------------------------------

async function run() {
	const slugs = listExplainerSlugs();
	if (slugs.length === 0) {
		console.log('No explainers found under static/explainers/. Nothing to do.');
		return;
	}

	const filtered = slugFilter ? slugs.filter((s) => s === slugFilter) : slugs;
	if (slugFilter && filtered.length === 0) {
		console.error(`No explainer with slug "${slugFilter}" — got: ${slugs.join(', ')}`);
		process.exit(1);
	}

	for (const slug of filtered) {
		const images = listSourceImages(slug);
		if (images.length === 0) {
			console.log(`[${slug}] no images under static/explainers/${slug}/images/ — skipping.`);
			continue;
		}

		console.log(`[${slug}] processing ${images.length} image(s)…`);
		const manifest = [];

		for (const image of images) {
			console.log(`  · ${image.name}`);
			const entry = await processImage({ slug, srcAbs: image.srcAbs, name: image.name });
			manifest.push(entry);
		}

		const out = writeManifest(slug, manifest);
		console.log(`[${slug}] manifest → ${out}\n`);
	}
}

run().catch((err) => {
	console.error(err);
	process.exit(1);
});
